# https://hub.docker.com/_/mysql
# host: localhost
# port: 8080
# db:   example
# user: example
# pass: example

version: "3"

services:
  mysql_db:
    restart: on-failure
    container_name: mysql_db
    image: mysql:latest
    ports:
      - "8080:8080"
    volumes:
      - "./conf/:/etc/mysql/conf.d/"
      - "./mysql_db/:/var/lib/mysql/"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=example
    networks:
      - mysql_db_network

networks:
  mysql_db_network:
