version: "3"

services:
  wikijs:
    restart: on-failure
    container_name: wikijs
    image: linuxserver/wikijs
    ports:
      - 3000:3000
    volumes:
      - path-to-config:/config
      - path-to-data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - wiki_network

networks:
  wiki_network:
