version: "3"

services:
  portainer:
    restart: on-failure
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    command: -H unix:///var/run/docker.sock --admin-password=123456
    networks:
      - portainer_network

volumes:
  portainer_data:

networks:
  portainer_network:
