version: "3"

services:
  watchtower:
    restart: on-failure
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      # - /root/.docker/config.json:/config.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$DOCKER_CERT_PATH:/etc/ssl/docker"
    environment:
      - REPO_USER=username
      - REPO_PASS=password
      - DOCKER_HOST="tcp://10.0.1.2:2375"
      - DOCKER_CERT_PATH=/etc/ssl/docker
    command: --run-once --interval 30 nginx redis
    networks:
      - watchtower_network

networks:
  watchtower_network:
