- type: log
  enabled: true

  paths:
    - /var/log/supervisor/app-test-stderr.log
    - /var/log/supervisor/app-test-stderr.log

  symlinks: true

  include_lines: ["WARNING", "ERROR"]

  tags: ["app", "test", "escapelife"]

  multiline.pattern: '^\[?[0-9]{4}-[0-9]{2}-[0-9]{2} [0-2][0-9]:[0-5][0-9]:[0-5][0-9],[0-9]{3}'
  multiline.negate: true
  multiline.match: after
